# Generated by Django 4.2.7 on 2025-03-24 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_remplissage', models.DateField(default=django.utils.timezone.now)),
                ('date_naissance', models.DateField()),
                ('niveau_etude', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=10)),
                ('taille', models.FloatField()),
                ('poids', models.FloatField()),
                ('situation_matrimoniale', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('arrondissement_residence', models.CharField(max_length=50)),
                ('quartier_residence', models.CharField(max_length=50)),
                ('age', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_non_eligibilite', models.CharField(blank=True, max_length=255, null=True)),
                ('porteur_hiv', models.BooleanField(default=False)),
                ('porteur_hbs', models.BooleanField(default=False)),
                ('porteur_hcv', models.BooleanField(default=False)),
                ('opere', models.BooleanField(default=False)),
                ('drepanocytaire', models.BooleanField(default=False)),
                ('diabetique', models.BooleanField(default=False)),
                ('hypertendu', models.BooleanField(default=False)),
                ('asthmatique', models.BooleanField(default=False)),
                ('cardiaque', models.BooleanField(default=False)),
                ('tatoue', models.BooleanField(default=False)),
                ('scarifie', models.BooleanField(default=False)),
                ('donneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Don.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='AutresRaisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_supplementaire', models.TextField()),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Don.donneur')),
            ],
        ),
    ]
