# Generated by Django 4.2.7 on 2025-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0002_remove_taille_from_donneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionssante',
            name='dernier_don',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionssante',
            name='maladie_chronique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='conditionssante',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionssante',
            name='taille',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donneur',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
