# Generated by Django 4.2.7 on 2025-03-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0003_conditionssante_dernier_don_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionssante',
            name='date_scarification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionssante',
            name='date_tatouage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditionssante',
            name='donneur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_sante', to='Don.donneur'),
        ),
        migrations.AlterField(
            model_name='conditionssante',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
