# Generated by Django 4.2.7 on 2025-03-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0004_conditionssante_date_scarification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneur',
            name='est_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditionssante',
            name='donneur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditionssante', to='Don.donneur'),
        ),
    ]
