# Generated by Django 4.2.7 on 2025-03-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Don', '0005_donneur_est_eligible_alter_conditionssante_donneur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AddField(
            model_name='donneur',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
